name: Egress Tests

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'components/egress/**'
      - 'components/internal/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.0'

      - name: Run Build
        working-directory: components/egress
        run: |
          go vet ./...
          go build .

      - name: Run tests
        working-directory: components/egress
        run: |
          go test ./...

  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run dns test
        working-directory: components/egress
        run: |
          chmod +x tests/smoke-dns.sh
          ./tests/smoke-dns.sh

      - name: Run nft test
        working-directory: components/egress
        run: |
          chmod +x tests/smoke-nft.sh
          ./tests/smoke-nft.sh

      - name: Run dynamic ip test
        working-directory: components/egress
        run: |
          chmod +x tests/smoke-dynamic-ip.sh
          ./tests/smoke-dynamic-ip.sh

  bench:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run bench test
        working-directory: components/egress
        run: |
          chmod +x tests/bench-dns-nft.sh
          ./tests/bench-dns-nft.sh
        env:
          BENCH_SAMPLE_SIZE: "20"

      - name: Upload egress logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: egress-log-for-bench
          path: /tmp/egress-logs/
          retention-days: 5
